name: Keep Render App Alive

on:
  schedule:
    - cron: '*/10 * * * *'  # Runs every 10 minutes

jobs:
  keep_alive:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render App
        run: curl -s "https://yt2mp3-rhan.onrender.com" > /dev/null
